### ISSUE TITLE
Cette ligne c'est pas du sql

### ISSUE THREAD

**Issue by DrBlackWolf** [Thomasfds/intersect-cms-unleashed#13]
`ALTER TABLE cms_news ADD CONSTRAINT FK_DA45342D12469DE2 FOREIGN KEY (category_id) REFERENCES cms_news_category (id)`

y'a 2 erreurs dans la ligne: 
- `FOREIGN KEY (category_id)` il manque la table
- ah et oui il faut ajouter un ";" a la fin c'est a peine la base en sql 🥸

**Comment by Thomasfds** [comment]
Bug fix.
