### ISSUE TITLE
Website graphic bug

### ISSUE THREAD

**Issue by worldofjimmy** [Thomasfds/intersect-cms-unleashed#23]
When opening a news on CMS website the "main article .header h2" is not at bottom.
Bottom is 40px but should be 0px but then its not visible on front page.

![image](https://user-images.githubusercontent.com/54074317/150739972-2e5df920-71e9-4458-927b-e84a739a0c24.png)

**Comment by Thomasfds** [comment]
I have check all code i see bottom:0 in code oO

**Comment by worldofjimmy** [comment]
I copied stylesheet.css from BritaniaR to Britantia and then this was solved. 
What is difference between BritaniaR and Britania? @Thomasfds

**Comment by Thomasfds** [comment]
> I copied stylesheet.css from BritaniaR to Britantia and then this was solved. What is difference between BritaniaR and Britania? @Thomasfds

The difference is design of sidebar
